services:
  rabbitmq:
    image: 'rabbitmq:management'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=guest'
      - 'RABBITMQ_DEFAULT_USER=guest'
    ports:
      - '5672:5672'
      - '15672:15672'

  servicebus-emulator:
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    container_name: servicebus-emulator
    pull_policy: always
    volumes:
      - ./servicebus/config.json:/ServiceBus_Emulator/ConfigFiles/Config.json
    ports:
      - '5673:5672'
      - '5300:5300'
    environment:
      SQL_SERVER: servicebus-mssql
      MSSQL_SA_PASSWORD: ${SERVICE_BUS_MSSQL_PASSWORD:-ServiceBus123!}
      ACCEPT_EULA: Y
      EMULATOR_HTTP_PORT: 5300
    depends_on:
      - servicebus-mssql
    networks:
      - default

  servicebus-mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: servicebus-mssql
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ${SERVICE_BUS_MSSQL_PASSWORD:-ServiceBus123!}
    networks:
      - default
