spring.application.name=connector

# Azure Service Bus emulator (see compose.yaml)
servicebus.connection-string=Endpoint=sb://localhost:5673;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;
servicebus.topic-name=playground-topic
servicebus.subscription-name=playground-subscription
